# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

consensus_cluster_cpp <- function(data, k_range, iterations, distance_method, subsample_ratio, feature_ratio) {
    .Call(`_ConsensusCluster_consensus_cluster_cpp`, data, k_range, iterations, distance_method, subsample_ratio, feature_ratio)
}

